### ISSUE TITLE
rancher2 bootstrap gives `unsupported protocol scheme ""` error

### ISSUE THREAD

**Issue by haydockjp** [terraform-providers/terraform-provider-rancher#105]
### Terraform Version
Terraform v0.12.23
+ provider.aws v2.52.0
+ provider.rancher2 v1.7.2

### Affected Resource(s)
Please list the resources as a list, for example:
- rancher2 provider

### Terraform Configuration Files
provider.tf
```hcl
provider "aws" {
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
  region     = var.aws_region
  version = ">= 2.38.0"
}

provider "rancher2" {
  alias = "bootstrap"

  api_url   = "https://${var.environment}${var.rancher2_api_url_suffix}"
  bootstrap = true
  insecure = true
}

resource "rancher2_bootstrap" "admin" {
  provider = rancher2.bootstrap

  current_password = var.admin_password
  password = var.admin_password
  telemetry = false
  token_update = true
}

provider "rancher2" {
  alias = "admin"

  api_url = rancher2_bootstrap.admin.url
  token_key = rancher2_bootstrap.admin.token
  insecure = true
}

output "bootstrap" {
  value = [
    rancher2_bootstrap.admin
  ]
}
```

project.tf
```hcl
data "rancher2_cluster" "main" {
  provider = rancher2.admin

  name = var.cluster_name
}

resource "rancher2_project" "infra" {
  provider = rancher2.admin

  name = "infrastructure"
  cluster_id = data.rancher2_cluster.main.id
  wait_for_cluster = true
}

resource "rancher2_namespace" "storage" {
  provider = rancher2.admin

  name = "storage"
  project_id = rancher2_project.infra.id
  wait_for_cluster = true
}

resource "rancher2_namespace" "containers" {
  provider = rancher2.admin

  name = "containers"
  project_id = rancher2_project.infra.id
  wait_for_cluster = true
}

```

### Debug Output
https://gist.github.com/haydockjp/7f9fa93ca3f566aa50ffa162a8944091

### Panic Output
None

### Expected Behavior
- Connect to rancher2, using boostrap
- Connect to rancher2, using access token from bootstrap
- Create a project and three name spaces

### Actual Behavior
- Error message trying to access the rancher2 resources using `provider rancher2.admin`
```
Error: Get : unsupported protocol scheme ""

  on project.tf line 1, in data "rancher2_cluster" "main":
   1: data "rancher2_cluster" "main" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
I have a shell script that takes arguments and then calls terraform docker container
```
docker run -i -t -e TF_LOG=TRACE -v $(pwd):/terraform -w /terraform hashicorp/terraform:light ${ACTION} \
-var environment=${ENVIRONMENT} \
-var cluster_name=${CLUSTER_NAME} \
-state=/terraform/state/${KEY}.tfstate \
| tee logs/${KEY}.log
```

### Important Factoids
- Running in EC2

**Note:**
I have other files that do other rancher2 and aws actions.
If I remove all but the provider.tf file, the access token is created. If I add back the other files after that token is stored in the state, it works.

If I have at least one file that accesses the rancher2.admin provider, it fails to access rancher2.

It seems that when I run apply, when it tries to workout what should be done, before doing anything, it does not create the api token in rancher 2 and therefore cannot access rancher 2.

**Comment by HighwayofLife** [comment]
I can confirm this is a problem and was able to reproduce it with a similar config.

Error:
```
Error: Rancher is not ready: Doing get: Get /ping: unsupported protocol scheme ""

  on main.tf line 99, in data "rancher2_user" "rancher-admin":
  99: data "rancher2_user" "rancher-admin" {
```

```hcl
# Configure the Rancher2 provider to bootstrap and admin
# Provider config for bootstrap
provider "rancher2" {
  alias = "bootstrap"

  api_url   = var.rancher_api_url
  bootstrap = true
}

# Create a new rancher2_bootstrap using bootstrap provider config
resource "rancher2_bootstrap" "admin" {
  provider = rancher2.bootstrap

  password  = data.azurerm_key_vault_secret.rancher_admin_password.value
  telemetry = true
}

# Provider config for admin
provider "rancher2" {
  alias = "admin"

  api_url   = rancher2_bootstrap.admin.url
  token_key = rancher2_bootstrap.admin.token
  insecure  = true
}

# Create a new rancher2 Auth Config Github
resource "rancher2_auth_config_github" "github" {
  provider = rancher2.admin

  client_id     = var.github.oauth.client_id
  client_secret = data.azurerm_key_vault_secret.oauth_client_secret.value
  hostname      = var.github.hostname
  enabled       = true
}

terraform {
  required_providers {
    github = {
      version = "= 2.4.1"
    }
  }
}

provider "github" {
  token        = data.azurerm_key_vault_secret.build-robot-pat.value
  organization = var.github.org
  base_url     = var.github.base_url

  version = "~> 2.4.1"
}

data "github_team" "rancher-admins" {
  slug = "rancher-admins"
}

data "github_user" "rancher-admin" {
  for_each = toset(data.github_team.rancher-admins.members)
  username = each.value
}

data "rancher2_user" "rancher-admin" {
  provider = rancher2.admin

  for_each    = { for u in data.github_user.rancher-admin : u.id => u.name }
  is_external = true
  name        = each.value
}

resource "rancher2_global_role_binding" "admin" {
  provider = rancher2.admin

  for_each       = { for u in data.rancher2_user.rancher-admin : u.id => u.name }
  name           = "shipyard-admin-${each.value}"
  global_role_id = "admin"
  user_id        = each.key
}
```

**Comment by BalkrishanAggarwal** [comment]
Any resolution for this `unsupported protocol scheme ""` error ?
Got the same with Google provider.
"Terraform/0.12.18%20%28+https://www.terraform.io%29%20Terraform-Plugin-SDK/2.0.3%20terraform-provider-google/3.42.0%20?alt=json": unsupported protocol scheme ""

What's the reason of this error ?

**Comment by rawmind0** [comment]
`rancher2` provider `api_url` should provide full Rancher url, including protocol. The provider config [example](https://registry.terraform.io/providers/rancher/rancher2/latest/docs#example-usage) is working fine. Seeing your examples, you are using a var for providing `api_url` and it seems this var is empty when the provider runs. That seems the reason of the error.  Are you using terraform modules?? Have you tested using the same config but setting `api_url` value instead of a var??

**Comment by mcanevet** [comment]
Well, this provider is about Rancher1 (up to v1.6.x). You should open an issue on Rancher2's provider repository : https://github.com/rancher/terraform-provider-rancher2

**Comment by rawmind0** [comment]
You are right @mcanevet, the issue is not on this provider. My answer applies to rancher2 provider
