### ISSUE TITLE
[Feature] Add ConfigMap resource just like Secret for projects/namespaces

### ISSUE THREAD

**Issue by mitchellmaler** [terraform-providers/terraform-provider-rancher#106]
Currently there is a secret resource but no configmap resource.

**Comment by raphink** [comment]
This provider is for Rancher 1 (Cattle), not Rancher 2 (Kubernetes).
You might want to look at https://github.com/terraform-providers/terraform-provider-rancher2

**Comment by mitchellmaler** [comment]
Oh wow yea I logged this to the wrong repo.
