### ISSUE TITLE
Unable to create environment with Github User

### ISSUE THREAD

**Issue by evilstream** [terraform-providers/terraform-provider-rancher#25]
### Terraform Version
v0.9.11

### Affected Resource(s)
- rancher_environent

### Terraform Configuration Files
```hcl
resource "rancher_environment" "default" {
  name = "${var.name}-${var.environment}"
  description = "tests"
  orchestration = "cattle"

  member {
    external_id = "28545307"
    external_id_type = "github_user"
    role = "owner"
  }
}
```

### Debug Output
https://gist.github.com/evilstream/31fc01d7acc700f1beb3e2f03b167206

### Expected Behavior
Environment should have been created when terraform apply was run.

### Actual Behavior
I get EOF error trying to apply the plan.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Run `terraform apply` with the given config.

**Comment by evilstream** [comment]
Also seeing the same EOF error when trying to create a registry credential. Think the issue is that it's using a global client instead of a an environment client since registries are scoped to an environment.

**Comment by evilstream** [comment]
Think I've found the issue, at least for the registries EOF error. Creating a registry credential seem to only work when using Environment API keys and not account keys. How do we create and manage environments though through terraform if we need the environment keys?

**Comment by mcanevet** [comment]
@evilstream it works for me with an account key but maybe it is because I'm admin. Are you admin?

**Comment by evilstream** [comment]
I'm not using admin credentials when running the terraform. Is that necessary?

**Comment by mcanevet** [comment]
@evilstream I'm not sure, could you try with an admin account's API keys to see if it works?

**Comment by mcanevet** [comment]
@evilstream this should be fixed since https://github.com/terraform-providers/terraform-provider-rancher/commit/3d860f8af13f1e02b7799d25b2bf1d310a27332b
