### ISSUE TITLE
Unable to create a nfs storage stack

### ISSUE THREAD

**Issue by leibowitz** [terraform-providers/terraform-provider-rancher#28]
### Terraform Version
terraform v0.9.11
Rancher 1.6.5

### Affected Resource(s)
- rancher_stack

### Terraform Configuration Files
```hcl
resource "rancher_stack" "nfs-driver" {
  environment_id = "1a10"
  name = "nfs"
  description = "Rancher NFS"
  catalog_id = "library:infra*nfs:4"
  scope = "system"
  start_on_create = true
  environment {
          MOUNT_DIR = "/"
          NFS_SERVER = "fs-99129d12.efs.eu-west-1.amazonaws.com"
  }
}

```

### Debug Output
Nothing interesting to see in it. But if needed, I can provide

### Panic Output
n/a

### Expected Behavior
The rancher-nfs stack status should be Running, and created as Infrastructure stack.

### Actual Behavior
The NFS stack is created as User stack, and is not able to start. Goes from Starting, to Running, to Stopped, and starts again.
```
10/08/2017 19:07:03 time="2017-08-10T18:07:03Z" level=info msg=Starting
10/08/2017 19:07:03 time="2017-08-10T18:07:03Z" level=fatal msg="getting driver ID: rancher-nfs is not a driver registered with the current Rancher environment"
```

### Steps to Reproduce
`terraform apply` with the config provided above and an freshly created environment

### Important Factoids
Created the NFS stack manually from the rancher UI works fine. In the UI, only the v0.3.0 shows as an option. I tried with both `catalog_id = "library:infra*nfs:3"` and `catalog_id = "library:infra*nfs:4"` - but it didn't seem to make any difference.
Reference to the catalog
https://github.com/rancher/rancher-catalog/tree/v1.6-release/infra-templates/nfs

According to https://forums.rancher.com/t/rancher-nfs-plugin-not-found/5110 the plugin should be present (in both directories).
/run/docker/plugins
/var/run/rancher/storage/

When creating the stack via terraform both directories are empty. When creating it via the Rancher UI, the plugin is created, and remains even after removing the stack. I tried again with terraform afterwards, but it still didn't work.

### References
- https://github.com/rancher/rancher/issues/9486
- https://github.com/terraform-providers/terraform-provider-rancher/issues/4
More specifically: https://github.com/hashicorp/terraform/issues/11771#issuecomment-298747815

**Comment by leibowitz** [comment]
After updating to terraform v0.10.0, it seems the stack is created correctly as an infrastructure stack. 

Also, using `library:infra*nfs:3` instead of `library:infra*nfs:4` seems to work fine on v0.10.0:
```
resource "rancher_stack" "nfs-driver" {
  environment_id = "1a10"
  name = "nfs"
  description = "Rancher NFS"
  catalog_id = "library:infra*nfs:3"
  scope = "system"
  start_on_create = true
  environment {
          MOUNT_DIR = "/"
          NFS_SERVER = "fs-99129d12.efs.eu-west-1.amazonaws.com"
  }
}
```

**Comment by grubernaut** [comment]
If I'm reading this correctly @leibowitz, looks like the issue is solved in `v0.10.0` for you?

**Comment by leibowitz** [comment]
Yep - all good

**Comment by JensPfeifle** [comment]
For anyone having the same issue with current versions of terraform, check that your are specifying scope = "system" and not "user".
