### ISSUE TITLE
Stack with system scope always marked as dirty

### ISSUE THREAD

**Issue by SerialVelocity** [terraform-providers/terraform-provider-rancher#34]
### Terraform Version
```sh
$ terraform -v
Terraform v0.10.4
```
Using `terraform-provider-rancher_v0.2.0_x4`
### Affected Resource(s)
rancher_stack

### Terraform Configuration Files
```hcl
resource "rancher_stack" "lb" {
  ...
  scope = "system"
}
```

### Expected Behaviour
After applying the resource, I would expect it not to be marked as dirty

### Actual Behaviour
Resource is marked as dirty so Terraform wants to push a modification

### Steps to Reproduce
1. `terraform apply`

**Comment by mcanevet** [comment]
Are you sure is it due to the fact that the stack is a system stack, or maybe you have the same issue explained in #35?

**Comment by SerialVelocity** [comment]
I'm assuming it is a different problem as I see this when running `terraform plan`:
```
scope:                    "user" => "system"
```

You could be right though

**Comment by mcanevet** [comment]
Hmm I think I also have this issue on some deployment but definitly not on all.

**Comment by SerialVelocity** [comment]
Ok, I just verified that it's a different problem. I fixed up all of my docker-compose and rancher-compose ymls to not have any changes according to terraform but it still thinks the scope is wrong.

**Comment by arsdehnel** [comment]
I have several stacks that I initially created as user scope and then change to system and that change doesn't seem to be managed properly in the state so terraform continually thinks that it needs to update it from user to system

**Comment by mcanevet** [comment]
OK, so this is definitely a bug.
