### ISSUE TITLE
Importing existing rancher hosts ends in failure to parse JSON

### ISSUE THREAD

**Issue by ekristen** [terraform-providers/terraform-provider-rancher#42]
```
json: cannot unmarshal array into Go struct field Project.data of type map[string]interface {}
```

### Terraform Version
```
Terraform v0.10.6
```

### Affected Resource(s)
Please list the resources as a list, for example:
- rancher_host

### Expected Behavior
The resource should be imported

### Actual Behavior
The JSON being returned by the Rancher API is not being marshaling into the go struct.

### Steps to Reproduce
1. `terraform import rancher_host.my-host 1h100

**Comment by ekristen** [comment]
It seems that it cannot import as it doesn't have an import function and/or it's querying the wrong endpoint.

**Comment by raphink** [comment]
`rancher_host` resources are not meant to be imported indeed. Creating them in Terraform imports them, because there is no way to create them. Once they are "created", they can be modified (e.g. labels) and destroyed.

**Comment by ekristen** [comment]
I'm not sure what you mean by it `imports them, because there is no way to create them`.

I basically have existing rancher environments, and hosts and I'd like to be able to import the hosts. It seems like you should be able to given that the host is queryable via the rancher api?

**Comment by raphink** [comment]
It's pointless to create hosts with the API: they are meant to be automatically created when you launch the Rancher agent on a node and it connects to the server.

For that reason, automating the node lifecycle is not practical by creating nodes in Terraform. Instead, the `rancher_node` provider detects if the node already exists in the API and "imports" it upon creation, which then allows it to manage it.

**Comment by raphink** [comment]
Said otherwise: if "import" wasn't managed in the creation process for nodes, then you'd need to import nodes manually every time you create new nodes, which would be very impractical. By managing it in create, it allows to do the following:

* create a node (using your favorite cloud provider)
* launch the Rancher agent on it (using a provisioner or user data)
* "create" the associated Rancher node (which will essentially "import" it, since it already exists)
* manage the Rancher node (labels, etc.)

**Comment by raphink** [comment]
Or maybe I've just been missing something in the Rancher docs...

**Comment by ekristen** [comment]
Except for terraform fails to import, I’m not asking it to create, I’m wanting the module to properly import the existing rancher host from the rancher api into the rancher_hosr resource but it does not do that.

**Comment by ekristen** [comment]
What’s?! They should absolutely be importable! 

An existing resource should be importable into terraform from rancher including a host. It just wasn’t calling the right API to do so.

I don’t agree with this change or the closure of this ticket.

If it’s not importable then why have this resource at all?!

**Comment by raphink** [comment]
Yes, theoretically it should. It just doesn't make sense with an automated workflow.

@mcanevet's PR rightly removed support for import because it wasn't implemented (for reasons listed above).

If you feel like implementing it, I'd welcome your PR (although I don't think it will be useful, since as I mentioned below creating the resource currently imports it).

**Comment by mcanevet** [comment]
@ekristen all you have to do is:
```hcl
rancher_host "foo.example.com" {
  environment_id = ...
  hostname = ...

  labels {
    foo = "bar"
  }
}
```
Then:
```shell
$ terraform apply
```
And it will import the resource in the statefile providing you have a host matching the hostname in the environment.
Then you'll be able to manage host labels from Terraform and remove the host from Rancher on destroy.

**Comment by ekristen** [comment]
Thanks @mcanevet. 

I understand why you've suggested this, not wanting to actually create hosts with terraform inside rancher makes sense when you aren't using a cloud provider config via rancher to spin the host up, therefore having the create "import" if the name and environment match make sense.

However with that said, I still think its wise to take the same import logic being used in the create function and support and import call so that the `rancher_host` resource works just like any other resource in terraform and so terraform can be used as expected.

What happens if the host doesn't already existing in the environment when the `rancher_host` resource is "created"? (I haven't had a chance to test this yet)

With that question asked, I'm starting to wonder, since rancher hosts are sorta unique with respect to how they get saved into rancher, I'm wondering if `rancher_host` should support driver configs so that a "proper" create can be performed via the API and then have special documentation or a special property on the `rancher_host` resource that should "import" in lieu of creation when driveConfigs are not present.
