### ISSUE TITLE
start_on_create: false doesn't work

### ISSUE THREAD

**Issue by SerialVelocity** [terraform-providers/terraform-provider-rancher#44]
Hey,

I don't have the time to fill in the template atm but I thought I'd file this now so I don't forget.

Setting `start_on_create: false` in the rancher_compose.yml doesn't seem to work.

Only other configuration that I think might be related is that I set the label `io.rancher.container.start_once: 'true'`

Best,
Ben

**Comment by mcanevet** [comment]
@SerialVelocity does it work when you use it with `rancher-compose`?

**Comment by mcanevet** [comment]
@SerialVelocity I close this because the problem does not come from this provider but from rancher itself  : https://github.com/rancher/rancher/issues/7287

**Comment by SerialVelocity** [comment]
Thanks for letting me know!
