### ISSUE TITLE
Missing resource state names, rancher provider

### ISSUE THREAD

**Issue by ajromito** [terraform-providers/terraform-provider-rancher#52]
Greetings Team,

I'm working on an issue we're seeing on a scheduled infrastructure job.  
(terraform apply in the morning, terraform destroy at night)

### Affected Resource(s)
- rancher_registration_token
- rancher_environment
- Potentially others

### Terraform Configuration Files
```
#Create the Rancher environment
resource "rancher_environment" "cd-dev" {
  name = "cd-dev"
  description = "Development environment"
  orchestration = "cattle"
}
```

### Error Output
* rancher_environment.cd-dev: Error waiting for environment (1a4800) to be created: unexpected state 'activating', wanted target 'active'. last error: %!s(<nil>)
also
* rancher_registration_token.cd-dev-token: Error waiting for registration token (1c4856) to be created: unexpected state 'activating', wanted target 'active'. last error: %!s(<nil>)
* * rancher_environment.cd-dev: Error waiting for environment (1a4833) to be created: unexpected state 'registering', wanted target 'active'. last error: %!s(<nil>)

### Expected Behavior
Expected that 'activating' and 'registering' be known states, and should continue polling for desired state.

### Actual Behavior
'activating' state unknown, terraform apply fails.

### Steps to Reproduce
Note:  I can only reproduce this issue on environment names that are frequently created/destroyed (and reused), implying that part of this issue may be increased response times on the rancher server or db side due to lack of housekeeping.

1. `terraform apply`

### Request
Add "activating" and "registering" to the list of pending states across applicable rancher resources

**Comment by mcanevet** [comment]
Fixed by #53
