### ISSUE TITLE
Feature request: manage rancher storage

### ISSUE THREAD

**Issue by jean-francois-labbe** [terraform-providers/terraform-provider-rancher#62]
### Terraform Version

Terraform v0.11.0
+ provider.aws v1.3.1
+ provider.rancher v1.1.1
+ provider.random v1.0.0
+ provider.template v1.0.0

### Request

Is it scheduled to support Rancher storage?

I would like to be able to create rancher storages with terraform.

**Comment by mcanevet** [comment]
Isn't it just system stacks that you can manage with `rancher_stack` resource?

**Comment by jean-francois-labbe** [comment]
I was able to deploy a rancher_stack (rancher-ebs) to manage rancher storage.
This is just one part of the problem.
This is working correctly if the storage volume is managed by rancher directly (meaning it is created when needed and destroyed when the service using it is removed) but there is another kind of storage which is "external" meaning rancher won't create or delete it you have to create it manually though the rancher UI. 

I use this kind of storage for database volumes.

I would like a terraform module to create this kind of volume.

**Comment by mcanevet** [comment]
@jean-francois-labbe fixed by https://github.com/terraform-providers/terraform-provider-rancher/pull/63
