### ISSUE TITLE
nil pointer due to inavlid previous state

### ISSUE THREAD

**Issue by aemneina** [terraform-providers/terraform-provider-rancher#68]
Not sure if there's enough info to figure out how or why this crashed. Issuing `terraform state rm <name>` unblocked the issue.

### Terraform Version
 0.11.1

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
https://gist.github.com/aemneina/531a51d395fc6b9ae54408903231e686

### Expected Behavior
Environment creation

### Actual Behavior
Panic and crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by raphink** [comment]
Hello. Indeed, I don't think there's enough info to reproduce and debug that crash. If you happen to stumble on it again, please provide a way to reproduce it.
