### ISSUE TITLE
rancher_host resource should be replaced on hostname change

### ISSUE THREAD

**Issue by eliaoggian** [terraform-providers/terraform-provider-rancher#82]
### Terraform Version
terraform 0.11.7
provider.rancher v1.2.1

### Affected Resource(s)
- rancher_host

### Terraform Configuration Files
```hcl
resource "rancher_host" "host" {
  count          = "${var.dev_hosts_count}"
  name           = "${random_pet.hostname.*.id[count.index]}.${var.dev_domain}"
  hostname       = "${random_pet.hostname.*.id[count.index]}.${var.dev_domain}"
  environment_id = "${data.rancher_environment.terraform.id}"

  lifecycle {
    create_before_destroy = true
  }

  depends_on = ["vsphere_virtual_machine.vm"]
}
```

### Debug Output
None.

### Panic Output
None.

### Expected Behavior
As a new vsphere_virtual_machine.vm resource is created, the hostname changes and there sould be a rancher_host resource replacement as well, the new host is created by the provisioner of the VM:

```hcl
  provisioner "remote-exec" {
    connection {
      type     = "ssh"
      user     = "root"
      password = "${var.root_password}"
    }

    inline = [
      # Add host to rancher
      "${rancher_registration_token.rancher-token.command}",

      # Wait for load balancer service to be up and running
      "sleep 20",
    ]
  }
```

### Actual Behavior
The rancher_host resource gets renamed, which results in having two hosts in rancher, one up and runnig and another one with the same name, which is the old VM that has been deleted.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. edit the vsphere_virtual_machine.vm resource template attribute which forces the replacement of the resource
3. `terraform apply`

### Important Factoids
This behaviour should be configurable on the rancher_host resource, with something like triggers or keepers on null_resource and random provider.  

### References
- https://github.com/hashicorp/terraform/issues/8099

**Comment by raphink** [comment]
@eliaoggian does  #86 fix this for you?

**Comment by eliaoggian** [comment]
@raphink I am not using the resource anymore as I am interacting directly with rancher's API. I will test it and report here if it's still causing the issue! Thanks

**Comment by raphink** [comment]
OK thanks.
