### ISSUE TITLE
Always shows changes when using yaml references

### ISSUE THREAD

**Issue by pvalsecc** [terraform-providers/terraform-provider-rancher#85]
### Terraform Version
Terraform v0.11.8                                                                                                                                  
+ provider.rancher v1.2.1                                                                                                                          
+ provider.template v1.0.0                                                                                                                         

### Affected Resource(s)
- rancher_stack

### Expected Behavior

When I use YAML anchors and references (`&` and `*`) in my docker-compose or rancher-compose, I expect the second `terraform apply` in a row to be a no-op.

### Actual Behavior
The second `terraform apply` in a row still see a difference

### Steps to Reproduce
Just use anchor and references in you YAML files and try to apply twice.

**Comment by mcanevet** [comment]
@pvalsecc we parse the yaml with libcompose to see the differences, so I guess this should be implemented in libcompose, not this provider.
