### ISSUE TITLE
can´t create stack with rancher_stack from docker_compose and rancher_compose

### ISSUE THREAD

**Issue by wolli-lenzen** [terraform-providers/terraform-provider-rancher#9]
### Terraform Version 0.9.8
Rancher Server v1.5.9

### Affected Resource(s)
Please list the resources as a list, for example:
- rancher_stack

### Terraform Configuration Files
```hcl
resource "rancher_stack" "test" {
  name           = "test"
  description    = "teststack"
  environment_id = "${data.terraform_remote_state.infrastructure.rancher_environment_id}"
  scope          = "user"
  docker_compose = <<EOF
    version: '2'
        services:
            web:
                image: nginx
  EOF
  rancher_compose = <<EOF
    version: '2'
    services:
        web:
            scale: 1
            start_on_create: true
  EOF
}
```

### Expected Behavior
Script should create the stack "test" and start a nginx container instance inside.

### Actual Behavior
Stack is created on rancher Server, but no service inside.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Error applying plan:

1 error(s) occurred:

* rancher_stack.test: 1 error(s) occurred:

* rancher_stack.test: Error waiting for stack (1e27) to be created: unexpected state 'error', wanted target 'active'. last error: %!s(<nil>)

**Comment by mcanevet** [comment]
Well, this is weird, we are using this everyday.
Do you always have this error?

**Comment by wolli-lenzen** [comment]
yes, always. Do you have the same versions?

**Comment by mcanevet** [comment]
@wolli-lenzen I think your `docker-compose.yml` is not valid.
`services` should not be indented.

**Comment by wolli-lenzen** [comment]
Oh shit - I see. Thanks for your hint, I will try again

**Comment by wolli-lenzen** [comment]
great, that was the mistake. Now it works great.
